export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $bannerSlider: document.querySelector('.banner-slider'),
  $marketing: document.querySelector('.marketing'),
  $catalogSlider: document.querySelector('.hero-catalog__slider'),
  $catalogFiltersTop: document.querySelectorAll('.catalog-filter__top'),
  $hideFilters: document.querySelector('.hide-filters'),
  $catalogColumns: document.querySelector('.catalog-columns__list'),
  $catalogGridContent: document.querySelector('.catalog-grid__content'),
  $catalogFilterItems: document.querySelectorAll('.catalog-filter__item'),
  $catalogChoise: document.querySelector('.catalog-choise'),
  $catalogCastomSelect: document.querySelectorAll('.custom-select'),
  $freeDelivery: document.querySelector('.free-delivery__btn'),
  $colorSelected: document.querySelector('.color-select'),
  $sizeSelected: document.querySelector('.size-select'),
  $stepper: document.querySelector('.stepper'),
  $sliderThumbs: document.querySelector('.card-slider__thumbs'),
  $sliderImg: document.querySelector('.card-slider__main img'),
  $cardBottomLinks: document.querySelectorAll('.card-descr__link'),
  $cardBottomLinks: document.querySelectorAll('.card-descr__link'),
  $cardRelatedSlider: document.querySelector('.card-related__slider'),
};
